fixed downloader invalid url flag and new docker copy
dod-advana/gamechanger-crawlers pull request #13
Opened 2021-05-28 16:47 UTC by meglynkau

2021-05-28 18:27 UTC, vctrstrm requested changes

2021-05-28 18:27 UTC, vctrstrm commented on paasJobs/scripts/gc_crawl_then_upload.sh
> +    "${CRAWLER_CONTAINER_IMAGE}"
let's put the `docker_run_status` right after the docker run command and make sleep 2 minutes (120), just to be sure

2021-05-30 16:14 UTC, takao8 approved these changes
both tests completed (full crawl/download) without issue. looks good!

2021-06-01 17:03 UTC, vctrstrm approved these changes

2021-06-01 18:54 UTC, merged